image: ubuntu

version: 1.0.{build}

install:
- ps: dotnet tool install --global coverlet.console

skip_tags: true

skip_branch_with_pr: true

skip_commits:
  files:
  - '**/*.txt'
  - '**/*.md'

matrix:
  fast_finish: true

configuration: Release

before_build:
  - ps: Copy-Item .\Secrets.Google.cs .\HardySoft.PhotosUploaderDownloader.Google\Security\Secrets.cs

build:
  project: photos-uploader-downloader.sln
  publish_core_console: true
  verbosity: minimal

dotnet_csproj:
  patch: true
  file: '**\*.csproj'
  version: '{version}'
  package_version: '{version}'
  assembly_version: '{version}'
  file_version: '{version}'
  informational_version: '{version}'

test_script:
  - dotnet test /p:CollectCoverage=true